application: crypto-catfish-89402
version: 1
runtime: go
api_version: go1

handlers:
- url: /images
  static_dir: images
- url: /.*
  script: _go_app
  secure: always

pagespeed:
  enabled_rewriters:
  - MinifyCss